=== stinger151/mythtv/mythtv/themes/mythuitheme.dtd
<!-- Parameter entities to avoid repetition -->
<!ENTITY % common_attributes "name CDATA #REQUIRED
                              from CDATA #IMPLIED" >
<!ENTITY % widgets "textarea|imagetype|statetype|button|buttonlist|buttontree|
                    textedit|checkbox|spinbox|progressbar|clock|webbrowser|
                    shape|guidegrid|editbar" >
<!ENTITY % widget_common "area|position|alpha|alphapulse|helptext|focusorder|
                           minsize|loadondemand" >

<!-- MythUI Theme Root -->
<!ELEMENT mythuitheme (window|fontdef|%widgets;)*>

<!-- Font Definition -->
<!ELEMENT fontdef (pixelsize|size|color|shadowcolor|shadowoffset|shadowalpha|
                   outlinecolor|outlinesize|outlinealpha|weight|
                   letterspacing|wordspacing|decoration)*>
<!ATTLIST fontdef %common_attributes;
                  face CDATA #IMPLIED>
<!ELEMENT pixelsize  (#PCDATA)>
<!ELEMENT size  (#PCDATA)>
<!ELEMENT color  (#PCDATA)>
<!ELEMENT shadowcolor  (#PCDATA)>
<!ELEMENT shadowoffset  (#PCDATA)>
<!ELEMENT shadowalpha  (#PCDATA)>
<!ELEMENT outlinecolor  (#PCDATA)>
<!ELEMENT outlinesize  (#PCDATA)>
<!ELEMENT outlinealpha  (#PCDATA)>
<!ELEMENT weight  (#PCDATA)>
<!ELEMENT letterspacing  (#PCDATA)>
<!ELEMENT wordspacing  (#PCDATA)>
<!ELEMENT decoration  (#PCDATA)>

<!-- Window/Screen -->
<!ELEMENT window (%widget_common;|fontdef|%widgets;)*>
<!ATTLIST window %common_attributes;>

<!-- Elements common to all widgets -->
<!ELEMENT area (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT alpha (#PCDATA)>
<!ELEMENT alphapulse EMPTY>
<!ATTLIST alphapulse min CDATA "0"
                     max CDATA "255"
                     change CDATA "5">
<!ELEMENT helptext (#PCDATA)>
<!ATTLIST helptext lang CDATA #IMPLIED>
<!ELEMENT focusorder (#PCDATA)>
<!ELEMENT minsize (#PCDATA)>
<!ELEMENT loadondemand (#PCDATA)>

<!-- Textarea Widget -->
<!ENTITY % textarea_elements "(case|font|cutdown|multiline|align|colorcycle|
                               scroll|value|template)">
<!ELEMENT textarea (%widget_common;|%textarea_elements;|%widgets;)*>
<!ATTLIST textarea %common_attributes;>
<!ELEMENT case (#PCDATA)>
<!ELEMENT font (#PCDATA)>
<!ATTLIST font state CDATA #IMPLIED>
<!ELEMENT cutdown (#PCDATA)>
<!ELEMENT multiline (#PCDATA)>
<!ELEMENT align (#PCDATA)>
<!ELEMENT colorcycle (#PCDATA)>
<!ATTLIST colorcycle start CDATA #IMPLIED
                     end CDATA #IMPLIED
                     steps CDATA #IMPLIED>
<!ELEMENT scroll (#PCDATA)> <!-- Not yet working -->
<!ATTLIST scroll direction (left|right|up|down) "left">
<!ELEMENT value (#PCDATA)>
<!ATTLIST value lang CDATA #IMPLIED>
<!ELEMENT template (#PCDATA)>
<!ATTLIST template type CDATA #IMPLIED>

<!-- Imagetype Widget -->
<!ELEMENT imagetype (%widget_common;|filename|alpha|preserveaspect|crop|
                     mask|reflection|grayscale|filepattern|delay|%widgets;)*>
<!ATTLIST imagetype %common_attributes;>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT preserveaspect (#PCDATA)>
<!ELEMENT crop (#PCDATA)>
<!ELEMENT mask (#PCDATA)>
<!ELEMENT reflection EMPTY>
<!ATTLIST reflection axis CDATA "horizontal"
                     shear CDATA "0"
                     scale CDATA "100"
                     length CDATA "100"
                     spacing CDATA "0">
<!ELEMENT grayscale (#PCDATA)>
<!ELEMENT greyscale (#PCDATA)>
<!ELEMENT filepattern (#PCDATA)>
<!ATTLIST filepattern low CDATA "0"
                       high CDATA #REQUIRED
                       cycle (start|reverse) "start"> <!-- delay CDATA "500" -->
<!ELEMENT delay (#PCDATA)>  <!-- DEPRECATED in future? Should be attribute of filepattern. -->

<!-- Shape Widget -->
<!ELEMENT shape (%widget_common;|type|cornerradius|fill|line|%widgets;)*>
<!ATTLIST shape %common_attributes;>
<!ELEMENT type (#PCDATA)>
<!ELEMENT fill (gradient*)>
<!ATTLIST fill color CDATA #IMPLIED
               alpha CDATA #IMPLIED
               style (solid|gradient) "solid">
<!ELEMENT gradient (stop*)>
<!ATTLIST gradient start CDATA #IMPLIED
                   end CDATA #IMPLIED
                   alpha CDATA #IMPLIED
                   direction (vertical|horizontal|diagonal) "vertical">
<!ELEMENT stop (#PCDATA)>
<!ATTLIST stop position CDATA #REQUIRED
               color CDATA #REQUIRED
               alpha CDATA #IMPLIED>
<!ELEMENT line (#PCDATA)>
<!ATTLIST line color CDATA "#000000"
               alpha CDATA "255"
               width CDATA "1"
               style (solid) "solid">
<!ELEMENT cornerradius (#PCDATA)>

<!-- Statetype Widget -->
<!ELEMENT statetype (%widget_common;|showempty|state|%widgets;)*>
<!ATTLIST statetype %common_attributes;>
<!ELEMENT showempty (#PCDATA)>
<!ELEMENT state (%widget_common;|fontdef|%widgets;)*>
<!ATTLIST state name CDATA #IMPLIED
                type CDATA #IMPLIED
                from CDATA #IMPLIED>

<!-- Clock Widget -->
<!ELEMENT clock (%widget_common;|%textarea_elements;|
                 %widgets;)*>
<!ATTLIST clock %common_attributes;>

<!-- Button Widget -->
<!ELEMENT button (%widget_common;|value|%widgets;)*> <!-- statetype -->
<!ATTLIST button %common_attributes;>

<!-- Buttonlist Widget -->
<!ENTITY % buttonlist_elements "layout|spacing|arrange|align|scrollstyle|
                                wrapstyle|showarrow|buttonarea|drawfrombottom">
<!ELEMENT buttonlist (%widget_common;|%buttonlist_elements;|%widgets;)*> <!-- statetype -->
<!ATTLIST buttonlist %common_attributes;>
<!ELEMENT layout (#PCDATA)>
<!ELEMENT spacing (#PCDATA)>
<!ELEMENT arrange (#PCDATA)>
<!ELEMENT scrollstyle (#PCDATA)>
<!ELEMENT wrapstyle (#PCDATA)>
<!ELEMENT showarrow (#PCDATA)>
<!ELEMENT buttonarea (#PCDATA)>
<!ELEMENT drawfrombottom (#PCDATA)>

<!-- Buttontree Widget -->
<!ELEMENT buttontree (%widget_common;|numlists|spacing|%widgets;)*> <!-- buttonlist -->
<!ATTLIST buttontree %common_attributes;>
<!ELEMENT numlists  (#PCDATA)>

<!-- Textedit Widget -->
<!ELEMENT textedit (%widget_common;|%widgets;)*> <!-- textarea|statetype|imagetype -->
<!ATTLIST textedit %common_attributes;>

<!-- Checkbox Widget -->
<!ELEMENT checkbox (%widget_common;|%widgets;)*> <!-- statetype -->
<!ATTLIST checkbox %common_attributes;>

<!-- Spinbox Widget -->
<!ELEMENT spinbox (%widget_common;|%buttonlist_elements;|template|%widgets;)*> <!-- statetype -->
<!ATTLIST spinbox %common_attributes;>

<!-- Progressbar Widget -->
<!ELEMENT progressbar (%widget_common;|layout|style|%widgets;)*> <!-- imagetype -->
<!ATTLIST progressbar %common_attributes;>
<!ELEMENT style (#PCDATA)>

<!-- Guidegrid Widget -->
<!ELEMENT guidegrid (%widget_common;|layout|channels|timeslots|solidcolor|
                     selector|showcategories|categoryalpha|recordingcolor|
                     conflictingcolor|cutdown|multiline|textoffset|recordstatus|
                     arrow|font|%widgets;)*>
<!ATTLIST guidegrid %common_attributes;>
<!ELEMENT channels  (#PCDATA)>
<!ELEMENT timeslots  (#PCDATA)>
<!ELEMENT solidcolor  (#PCDATA)>
<!ELEMENT selector EMPTY>
<!ATTLIST selector type (highlight|box|roundbox) #IMPLIED
                   linecolor CDATA #IMPLIED
                   fillcolor CDATA #IMPLIED>
<!ELEMENT showcategories  (#PCDATA)>
<!ELEMENT categoryalpha  (#PCDATA)>
<!ELEMENT recordingcolor  (#PCDATA)>
<!ELEMENT conflictingcolor  (#PCDATA)>
<!ELEMENT textoffset  (#PCDATA)>
<!ELEMENT recordstatus EMPTY>
<!ATTLIST recordstatus type (SingleRecord|TimeslotRecord|ChannelRecord|
                             AllRecord|WeekslotRecord|FindOneRecord|
                             OverrideRecord) #REQUIRED
                       image CDATA #REQUIRED>
<!ELEMENT arrow EMPTY>
<!ATTLIST arrow direction (left|right) #REQUIRED
                image CDATA #REQUIRED>

<!-- Webbrowser Widget -->
<!ELEMENT webbrowser (%widget_common;|url|zoom|background|userstylesheet|
                      updateinterval|%widgets;)*>
<!ATTLIST webbrowser %common_attributes;>
<!ELEMENT url (#PCDATA)>
<!ELEMENT zoom (#PCDATA)>
<!ELEMENT background (#PCDATA)>
<!ATTLIST background color CDATA #REQUIRED
                     alpha CDATA #IMPLIED>
<!ELEMENT userstylesheet (#PCDATA)>
<!ELEMENT updateinterval (#PCDATA)>

<!-- Editbar Widget -->
<!ELEMENT editbar (%widget_common;|%widgets;)*>
<!ATTLIST editbar %common_attributes;>

=== stinger151/mythtv/mythtv/themes/Terra/browser-ui.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mythuitheme SYSTEM "http://www.mythtv.org/schema/mythuitheme.dtd">
<mythuitheme>

    <window name="bookmarkmanager">

        <imagetype name="backdrop" from="basebackdrop" />

        <imagetype name="topbar" from="basetopbar" />

        <textarea name="heading" from="baseheading">
            <value>Bookmark Manager</value>
        </textarea>

        <buttonlist name="bookmarklist">
            <area>39,97,600,588</area>
            <layout>vertical</layout>
            <spacing>0</spacing>
            <buttonarea>25,0,600,588</buttonarea>
            <statetype name="buttonitem">
                <area>0,0,595,84</area>
                <state name="active">
                    <area>0,0,595,84</area>
                    <imagetype name="frame">
                        <filename>recordings/generallistbackground.png</filename>
                    </imagetype>
                    <textarea name="name" from="basetextarea">
                        <area>35,10,517,42</area>
                        <font>baselarge</font>
                        <align>vcenter</align>
                    </textarea>
                    <textarea name="url" from="basetextarea">
                        <area>35,58,450,30</area>
                        <font>basesmallbrown</font>
                        <align>vcenter</align>
                    </textarea>
                </state>
                <state name="selectedactive" from="active">
                    <imagetype name="frame">
                        <position>-19,0</position>
                        <filename>recordings/generallistselectedframe.png</filename>
                    </imagetype>
                    <textarea name="name">
                        <area>37,10,530,42</area>
                    </textarea>
                    <textarea name="url">
                        <position>37,58</position>
                    </textarea>
                </state>
                <state name="selectedinactive" from="active">
                </state>
            </statetype>
            <statetype name="upscrollarrow">
                <position>0,5</position>
                <state type="full">
                    <imagetype name="up">
                        <filename>shared/list_up_arrow.png</filename>
                    </imagetype>
                </state>
            </statetype>
            <statetype name="downscrollarrow">
                <position>0,564</position>
                <state type="full">
                    <imagetype name="down">
                        <filename>shared/list_down_arrow.png</filename>
                    </imagetype>
                </state>
            </statetype>
        </buttonlist>

        <imagetype name="groupframe">
            <position>0,57</position>
            <filename>recordings/groupframe.png</filename>
        </imagetype>

        <buttonlist name="grouplist">
            <area>0,60,1280,40</area>
            <spacing>15</spacing>
            <scrollstyle>center</scrollstyle>
            <wrapstyle>items</wrapstyle>
            <layout>horizontal</layout>
            <buttonarea>12,0,1260,40</buttonarea>
            <statetype name="buttonitem">
                <state name="active">
                    <area>0,0,240,40</area>
                    <textarea name="buttontext" from="basetextarea">
                        <area>4,3,232,36</area>
                        <align>allcenter</align>
                        <cutdown>yes</cutdown>
                        <font>basemedium</font>
                        <alpha>220</alpha>
                    </textarea>
                </state>
                <state name="selectedactive" from="active">
                    <textarea name="buttontext">
                        <area>4,1,232,36</area>
                        <font>basemediumbrown</font>
                        <alpha>255</alpha>
                    </textarea>
                </state>
                <state name="selectedinactive" from="selectedactive" />
            </statetype>
            <statetype name="downscrollarrow">
                <position>1264,0</position>
                <state type="full">
                    <imagetype name="right">
                        <filename>shared/horizlist_internal_right_arrow.png</filename>
                    </imagetype>
                </state>
            </statetype>
            <statetype name="upscrollarrow">
                <position>0,0</position>
                <state type="full">
                    <imagetype name="left">
                        <filename>shared/horizlist_internal_left_arrow.png</filename>
                    </imagetype>
                </state>
            </statetype>
        </buttonlist>

        <textarea name="messagetext" from="basetextarea">
            <font>basemedium</font>
            <area>40,230,720,290</area>
            <align>allcenter</align>
            <multiline>yes</multiline>
        </textarea>

    </window>

    <window name="browser">

        <imagetype name="backdrop" from="basebackdrop" />

        <imagetype name="topbar" from="basetopbar" />

        <textarea name="title" from="baseheading">
            <value>Web Page</value>
        </textarea>

        <webbrowser name="webbrowser">
            <area>20,55,1240,620</area>
            <zoom>1.4</zoom>
        </webbrowser>

        <buttonlist name="pagelist" from="baseselector">
            <position>20,685</position>
        </buttonlist>

    </window>

    <window name="browserconfig">
        <imagetype name="topbar" from="basetopbar" />
        <textarea name="title" from="baseheading">
            <value>Rating Settings</value>
        </textarea>

        <!--textarea name="title" from="basetextarea">
            <font>baselarge</font>
            <area>0,50,1280,50</area>
            <align>allcenter</align>
        </textarea-->

        <textarea name="commandlabel" from="basetextarea">
            <area>130,150,300,30</area>
            <align>right,vcenter</align>
            <value>Browser Command:</value>
        </textarea>

        <textedit name="command" from="basetextedit">
            <position>445,140</position>
        </textedit>

        <textarea name="zoomlabel" from="commandlabel">
            <position>130,250</position>
            <align>right,vcenter</align>
            <value>Text Size:</value>
        </textarea>

        <textedit name="zoom" from="basetextedit">
            <position>445,240</position>
        </textedit>

        <textarea name="pluginlabel" from="commandlabel">
           <position>130,350</position>
            <value>Enable plugins:</value>
        </textarea>

        <checkbox name="enablepluginscheck" from="basecheckbox">
            <position>445,350</position>
        </checkbox>

        <shape name="background">
            <area>200,420,800,140</area>
            <type>roundbox</type>
            <fill color="#000000" alpha="70" />
            <cornerradius>8</cornerradius>
        </shape>

        <textarea name="description" from="basetextarea">
            <area>210,430,780,120</area>
            <multiline>yes</multiline>
        </textarea>

        <button name="cancel" from="basebutton">
            <position>250,620</position>
            <value>Cancel</value>
        </button>

        <button name="ok" from="basebutton">
            <position>880,620</position>
            <value>OK</value>
        </button>

    </window>

</mythuitheme>

=== stinger151/mythtv/mythtv/themes/Terra/gallery-ui.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mythuitheme SYSTEM "http://www.mythtv.org/schema/mythuitheme.dtd">
<mythuitheme>

    <window name="gallery">

        <imagetype name="fanart" from="basebackdrop" />

        <imagetype name="topbar" from="basetopbar" />

        <textarea name="heading" from="baseheading">
            <value>Image Gallery</value>
        </textarea>

        <buttonlist name="images">
            <area>37,50,1250,690</area>
            <layout>grid</layout>
            <spacing>2</spacing>
            <buttonarea>0,0,1250,675</buttonarea>
            <statetype name="buttonitem">
                <state name="active">
                    <area>0,0,200,209</area>
                    <imagetype name="buttonbackground">
                        <filename>video/video_gallery_background.png</filename>
                    </imagetype>

                    <imagetype name="buttonimage">
                        <area>6,5,187,145</area>
                        <preserveaspect>true</preserveaspect>
                    </imagetype>

                    <statetype name="nodetype">
                        <position>118,83</position>
                        <state name="subfolder">
                            <imagetype name="icon">
                                <filename>shared/directory.png</filename>
                                <preserveaspect>yes</preserveaspect>
                            </imagetype>
                        </state>
                        <state name="upfolder" from="subfolder">
                            <imagetype name="upnode">
                                <position>37,34</position>
                                <filename>shared/updirectory.png</filename>
                            </imagetype>
                        </state>
                    </statetype>
                    <textarea name="buttontext" from="basetextarea">
                        <area>8,155,183,50</area>
                        <align>hcenter,vcenter</align>
                        <multiline>true</multiline>
                    </textarea>
                    <textarea name="childcount" from="basetextarea">
                        <area>144,118,35,20</area>
                        <font>basesmallbrown</font>
                        <align>hcenter</align>
                    </textarea>
                    <statetype name="buttoncheck">
                        <position>10,105</position>
                        <showempty>yes</showempty>
                        <state type="full">
                            <imagetype name="overlay">
                                <filename>recordings/statusoverlay.png</filename>
                            </imagetype>
                            <imagetype name="watchedimage">
                                <position>4,4</position>
                                <filename>shared/playlist.png</filename>
                            </imagetype>
                        </state>
                    </statetype>
                </state>
                <state name="selectedactive" from="active">
                    <imagetype name="buttonbackground">
                        <filename>video/video_gallery_background_selected.png</filename>
                    </imagetype>
                </state>
            </statetype>
        </buttonlist>

        <!-- optional - shows a message when no images are available
             in the current directory -->
        <textarea name="noimages" from="basetextarea">
            <area>15,20,1250,680</area>
            <font>basemedium</font>
            <align>allcenter</align>
            <value>No images found in configured directory.  Are you sure you have set up the plugin properly?</value>
        </textarea>

    </window>

</mythuitheme>

=== stinger151/mythtv/mythtv/themes/MythCenter-wide/status-ui.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mythuitheme SYSTEM "http://www.mythtv.org/schema/mythuitheme.dtd">
<mythuitheme>

    <window name="status">

        <textarea name="heading">
            <area>30,10,740,40</area>
            <font>baselarge</font>
            <value>System Status</value>
        </textarea>

        <shape name="list_background" from="basebackground">
            <area>30,94,1220,390</area>
        </shape>

        <buttonlist name="category">
            <area>70,44,1250,44</area>
            <layout>horizontal</layout>
            <spacing>6</spacing>
            <buttonarea>24,0,1220,44</buttonarea>
            <triggerevent context="Global" action="ESCAPE">UP</triggerevent>
            <statetype name="buttonitem">
                <state name="active">
                    <area>0,0,214,44</area>
                    <shape name="background" from="basewidgetshape" />
                    <textarea name="buttontext" from="basetextarea">
                        <area>4,2,206,40</area>
                        <font>basesmall</font>
                        <align>allcenter</align>
                    </textarea>
                </state>
                <state name="selectedactive" from="active">
                    <shape name="background" from="baseselectedwidgetshape" />
                </state>
                <state name="selectedinactive" from="active">
                    <textarea name="buttontext">
                        <font>basesmall</font>
                    </textarea>
                </state>
            </statetype>
            <statetype name="downscrollarrow">
                <position>1134,12</position>
                <state type="off">
                    <imagetype name="dnon">
                        <filename>lb-rtarrow-reg.png</filename>
                    </imagetype>
                </state>
                <state type="full">
                    <imagetype name="dnoff">
                        <filename>lb-rtarrow-sel.png</filename>
                    </imagetype>
                </state>
            </statetype>
            <statetype name="upscrollarrow">
                <position>-2,12</position>
                <state type="off">
                    <imagetype name="upon">
                        <filename>lb-ltarrow-reg.png</filename>
                    </imagetype>
                </state>
                <state type="full">
                    <imagetype name="upoff">
                        <filename>lb-ltarrow-sel.png</filename>
                    </imagetype>
                </state>
            </statetype>
        </buttonlist>

        <buttonlist name="log" from="basebuttonlist2">
            <position>18,108</position>
            <searchposition>-1,490</searchposition>
        </buttonlist>

        <textarea name="helplabel">
            <area>30,490,740,30</area>
            <value>Details</value>
            <font>basemedium</font>
        </textarea>

        <textarea name="helptext" from="basetextarea">
            <area>40,530,1200,150</area>
            <value>This screen displays the status of various system components</value>
            <multiline>yes</multiline>
        </textarea>

    </window>

</mythuitheme>
