=== stinger151/mythtv/mythtv/themes/mythuitheme.dtd
<!-- Parameter entities to avoid repetition -->
<!ENTITY % common_attributes "name CDATA #REQUIRED
                              from CDATA #IMPLIED" >
<!ENTITY % widgets "textarea|imagetype|statetype|button|buttonlist|buttontree|
                    textedit|checkbox|spinbox|progressbar|clock|webbrowser|
                    shape|guidegrid|editbar" >
<!ENTITY % widget_common "area|position|alpha|alphapulse|helptext|focusorder|
                           minsize|loadondemand" >

<!-- MythUI Theme Root -->
<!ELEMENT mythuitheme (window|fontdef|%widgets;)*>

<!-- Font Definition -->
<!ELEMENT fontdef (pixelsize|size|color|shadowcolor|shadowoffset|shadowalpha|
                   outlinecolor|outlinesize|outlinealpha|weight|
                   letterspacing|wordspacing|decoration)*>
<!ATTLIST fontdef %common_attributes;
                  face CDATA #IMPLIED>
<!ELEMENT pixelsize  (#PCDATA)>
<!ELEMENT size  (#PCDATA)>
<!ELEMENT color  (#PCDATA)>
<!ELEMENT shadowcolor  (#PCDATA)>
<!ELEMENT shadowoffset  (#PCDATA)>
<!ELEMENT shadowalpha  (#PCDATA)>
<!ELEMENT outlinecolor  (#PCDATA)>
<!ELEMENT outlinesize  (#PCDATA)>
<!ELEMENT outlinealpha  (#PCDATA)>
<!ELEMENT weight  (#PCDATA)>
<!ELEMENT letterspacing  (#PCDATA)>
<!ELEMENT wordspacing  (#PCDATA)>
<!ELEMENT decoration  (#PCDATA)>

<!-- Window/Screen -->
<!ELEMENT window (%widget_common;|fontdef|%widgets;)*>
<!ATTLIST window %common_attributes;>

<!-- Elements common to all widgets -->
<!ELEMENT area (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT alpha (#PCDATA)>
<!ELEMENT alphapulse EMPTY>
<!ATTLIST alphapulse min CDATA "0"
                     max CDATA "255"
                     change CDATA "5">
<!ELEMENT helptext (#PCDATA)>
<!ATTLIST helptext lang CDATA #IMPLIED>
<!ELEMENT focusorder (#PCDATA)>
<!ELEMENT minsize (#PCDATA)>
<!ELEMENT loadondemand (#PCDATA)>

<!-- Textarea Widget -->
<!ENTITY % textarea_elements "(case|font|cutdown|multiline|align|colorcycle|
                               scroll|value|template)">
<!ELEMENT textarea (%widget_common;|%textarea_elements;|%widgets;)*>
<!ATTLIST textarea %common_attributes;>
<!ELEMENT case (#PCDATA)>
<!ELEMENT font (#PCDATA)>
<!ATTLIST font state CDATA #IMPLIED>
<!ELEMENT cutdown (#PCDATA)>
<!ELEMENT multiline (#PCDATA)>
<!ELEMENT align (#PCDATA)>
<!ELEMENT colorcycle (#PCDATA)>
<!ATTLIST colorcycle start CDATA #IMPLIED
                     end CDATA #IMPLIED
                     steps CDATA #IMPLIED>
<!ELEMENT scroll (#PCDATA)> <!-- Not yet working -->
<!ATTLIST scroll direction (left|right|up|down) "left">
<!ELEMENT value (#PCDATA)>
<!ATTLIST value lang CDATA #IMPLIED>
<!ELEMENT template (#PCDATA)>
<!ATTLIST template type CDATA #IMPLIED>

<!-- Imagetype Widget -->
<!ELEMENT imagetype (%widget_common;|filename|alpha|preserveaspect|crop|
                     mask|reflection|grayscale|filepattern|delay|%widgets;)*>
<!ATTLIST imagetype %common_attributes;>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT preserveaspect (#PCDATA)>
<!ELEMENT crop (#PCDATA)>
<!ELEMENT mask (#PCDATA)>
<!ELEMENT reflection EMPTY>
<!ATTLIST reflection axis CDATA "horizontal"
                     shear CDATA "0"
                     scale CDATA "100"
                     length CDATA "100"
                     spacing CDATA "0">
<!ELEMENT grayscale (#PCDATA)>
<!ELEMENT greyscale (#PCDATA)>
<!ELEMENT filepattern (#PCDATA)>
<!ATTLIST filepattern low CDATA "0"
                       high CDATA #REQUIRED
                       cycle (start|reverse) "start"> <!-- delay CDATA "500" -->
<!ELEMENT delay (#PCDATA)>  <!-- DEPRECATED in future? Should be attribute of filepattern. -->

<!-- Shape Widget -->
<!ELEMENT shape (%widget_common;|type|cornerradius|fill|line|%widgets;)*>
<!ATTLIST shape %common_attributes;>
<!ELEMENT type (#PCDATA)>
<!ELEMENT fill (gradient*)>
<!ATTLIST fill color CDATA #IMPLIED
               alpha CDATA #IMPLIED
               style (solid|gradient) "solid">
<!ELEMENT gradient (stop*)>
<!ATTLIST gradient start CDATA #IMPLIED
                   end CDATA #IMPLIED
                   alpha CDATA #IMPLIED
                   direction (vertical|horizontal|diagonal) "vertical">
<!ELEMENT stop (#PCDATA)>
<!ATTLIST stop position CDATA #REQUIRED
               color CDATA #REQUIRED
               alpha CDATA #IMPLIED>
<!ELEMENT line (#PCDATA)>
<!ATTLIST line color CDATA "#000000"
               alpha CDATA "255"
               width CDATA "1"
               style (solid) "solid">
<!ELEMENT cornerradius (#PCDATA)>

<!-- Statetype Widget -->
<!ELEMENT statetype (%widget_common;|showempty|state|%widgets;)*>
<!ATTLIST statetype %common_attributes;>
<!ELEMENT showempty (#PCDATA)>
<!ELEMENT state (%widget_common;|fontdef|%widgets;)*>
<!ATTLIST state name CDATA #IMPLIED
                type CDATA #IMPLIED
                from CDATA #IMPLIED>

<!-- Clock Widget -->
<!ELEMENT clock (%widget_common;|%textarea_elements;|
                 %widgets;)*>
<!ATTLIST clock %common_attributes;>

<!-- Button Widget -->
<!ELEMENT button (%widget_common;|value|%widgets;)*> <!-- statetype -->
<!ATTLIST button %common_attributes;>

<!-- Buttonlist Widget -->
<!ENTITY % buttonlist_elements "layout|spacing|arrange|align|scrollstyle|
                                wrapstyle|showarrow|buttonarea|drawfrombottom">
<!ELEMENT buttonlist (%widget_common;|%buttonlist_elements;|%widgets;)*> <!-- statetype -->
<!ATTLIST buttonlist %common_attributes;>
<!ELEMENT layout (#PCDATA)>
<!ELEMENT spacing (#PCDATA)>
<!ELEMENT arrange (#PCDATA)>
<!ELEMENT scrollstyle (#PCDATA)>
<!ELEMENT wrapstyle (#PCDATA)>
<!ELEMENT showarrow (#PCDATA)>
<!ELEMENT buttonarea (#PCDATA)>
<!ELEMENT drawfrombottom (#PCDATA)>

<!-- Buttontree Widget -->
<!ELEMENT buttontree (%widget_common;|numlists|spacing|%widgets;)*> <!-- buttonlist -->
<!ATTLIST buttontree %common_attributes;>
<!ELEMENT numlists  (#PCDATA)>

<!-- Textedit Widget -->
<!ELEMENT textedit (%widget_common;|%widgets;)*> <!-- textarea|statetype|imagetype -->
<!ATTLIST textedit %common_attributes;>

<!-- Checkbox Widget -->
<!ELEMENT checkbox (%widget_common;|%widgets;)*> <!-- statetype -->
<!ATTLIST checkbox %common_attributes;>

<!-- Spinbox Widget -->
<!ELEMENT spinbox (%widget_common;|%buttonlist_elements;|template|%widgets;)*> <!-- statetype -->
<!ATTLIST spinbox %common_attributes;>

<!-- Progressbar Widget -->
<!ELEMENT progressbar (%widget_common;|layout|style|%widgets;)*> <!-- imagetype -->
<!ATTLIST progressbar %common_attributes;>
<!ELEMENT style (#PCDATA)>

<!-- Guidegrid Widget -->
<!ELEMENT guidegrid (%widget_common;|layout|channels|timeslots|solidcolor|
                     selector|showcategories|categoryalpha|recordingcolor|
                     conflictingcolor|cutdown|multiline|textoffset|recordstatus|
                     arrow|font|%widgets;)*>
<!ATTLIST guidegrid %common_attributes;>
<!ELEMENT channels  (#PCDATA)>
<!ELEMENT timeslots  (#PCDATA)>
<!ELEMENT solidcolor  (#PCDATA)>
<!ELEMENT selector EMPTY>
<!ATTLIST selector type (highlight|box|roundbox) #IMPLIED
                   linecolor CDATA #IMPLIED
                   fillcolor CDATA #IMPLIED>
<!ELEMENT showcategories  (#PCDATA)>
<!ELEMENT categoryalpha  (#PCDATA)>
<!ELEMENT recordingcolor  (#PCDATA)>
<!ELEMENT conflictingcolor  (#PCDATA)>
<!ELEMENT textoffset  (#PCDATA)>
<!ELEMENT recordstatus EMPTY>
<!ATTLIST recordstatus type (SingleRecord|TimeslotRecord|ChannelRecord|
                             AllRecord|WeekslotRecord|FindOneRecord|
                             OverrideRecord) #REQUIRED
                       image CDATA #REQUIRED>
<!ELEMENT arrow EMPTY>
<!ATTLIST arrow direction (left|right) #REQUIRED
                image CDATA #REQUIRED>

<!-- Webbrowser Widget -->
<!ELEMENT webbrowser (%widget_common;|url|zoom|background|userstylesheet|
                      updateinterval|%widgets;)*>
<!ATTLIST webbrowser %common_attributes;>
<!ELEMENT url (#PCDATA)>
<!ELEMENT zoom (#PCDATA)>
<!ELEMENT background (#PCDATA)>
<!ATTLIST background color CDATA #REQUIRED
                     alpha CDATA #IMPLIED>
<!ELEMENT userstylesheet (#PCDATA)>
<!ELEMENT updateinterval (#PCDATA)>

<!-- Editbar Widget -->
<!ELEMENT editbar (%widget_common;|%widgets;)*>
<!ATTLIST editbar %common_attributes;>

=== stinger151/mythtv/mythtv/themes/default/settings-ui.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mythuitheme SYSTEM "http://www.mythtv.org/schema/mythuitheme.dtd">
<mythuitheme>

    <window name="rawsettingseditor">
        <textarea name="heading" from="basetextarea">
            <area>20,20,760,40</area>
            <align>allcenter</align>
            <font>basemedium</font>
        </textarea>

        <buttonlist name="settings" from="basebuttonlist">
            <area>20,80,400,320</area>
            <layout>vertical</layout>
            <spacing>5</spacing>
            <scrollstyle>free</scrollstyle>
            <wrapstyle>none</wrapstyle>
            <buttonarea>0,0,400,300</buttonarea>
        </buttonlist>

        <shape name="label-shape">
            <area>20,420,400,30</area>
            <type>roundbox</type>
            <fill color="#000000" alpha="130" />
            <cornerradius>4</cornerradius>
        </shape>

        <textarea name="label-text">
            <area>24,420,392,30</area>
            <font>basesmallgreen</font>
            <align>left,vcenter</align>
        </textarea>

        <shape name="background">
            <area>20,455,760,30</area>
            <type>roundbox</type>
            <fill color="#FFFFFF" />
            <cornerradius>4</cornerradius>
        </shape>

        <textedit name="settingvalue">
            <area>24,455,760,30</area>
            <imagetype name="cursor">
                <filename>cursor.png</filename>
            </imagetype>
            <textarea name="text">
                <area>5,0,750,30</area>
                <font>basesmallblack</font>
            </textarea>
        </textedit>

        <button name="cancel" from="basebutton">
            <position>20,540</position>
            <value>Cancel</value>
        </button>

        <button name="save" from="basebutton">
            <position>630,540</position>
            <value>Save</value>
        </button>

    </window>

    <window name="themechooser">
        <area>0,0,800,600</area>

        <shape name="background" from="basebackground">
            <area>0,0,800,600</area>
            <fill color="#000000" alpha="200" />
        </shape>

        <shape name="preview-shape">
            <area>410,50,380,285</area>
            <type>roundbox</type>
            <fill color="#000000" />
            <cornerradius>20</cornerradius>
        </shape>

        <imagetype name="preview">
            <area>425,65,350,260</area>
            <filename />
            <preserveaspect>true</preserveaspect>
        </imagetype>

        <textarea name="name" from="basetextarea">
            <area>425,350,350,30</area>
            <multiline>no</multiline>
            <font>basemedium</font>
            <align>left,vcenter</align>
            <cutdown>yes</cutdown>
        </textarea>

        <textarea name="resolution" from="basetextarea">
            <area>425,380,175,30</area>
            <multiline>no</multiline>
            <font>basesmall</font>
            <align>left,vcenter</align>
            <cutdown>yes</cutdown>
        </textarea>

        <textarea name="aspect" from="basetextarea">
            <area>600,380,175,30</area>
            <multiline>no</multiline>
            <font>basesmall</font>
            <align>left,vcenter</align>
            <cutdown>yes</cutdown>
        </textarea>

        <textarea name="description" from="basetextarea">
            <area>425,410,350,350</area>
            <multiline>yes</multiline>
            <font>basesmall</font>
            <align>left,top</align>
            <cutdown>yes</cutdown>
        </textarea>

        <buttonlist name="themes">
            <area>40,60,375,512</area>
            <scrollstyle>free</scrollstyle>
            <wrapstyle>items</wrapstyle>
            <layout>vertical</layout>
            <spacing>2</spacing>
            <drawfrombottom>false</drawfrombottom>
            <buttonarea>0,0,100%,95%</buttonarea>
            <statetype name="buttonitem">
                <state name="active">
                    <area>0,0,375,66</area>
                    <shape name="item">
                        <area>0,0,375,66</area>
                        <type>box</type>
                        <fill color="#000000" alpha="180" />
                    </shape>
                    <imagetype name="buttonimage">
                        <area>30,5,110,56</area>
                        <alpha>160</alpha>
                        <preserveaspect>true</preserveaspect>
                    </imagetype>
                    <textarea name="buttontext">
                        <area>150,5,281,56</area>
                        <align>left,vcenter</align>
                        <font>basesmall</font>
                        <alpha>210</alpha>
                    </textarea>

<!-- State to show whether a theme is locally installed or remotely downloadable
                    <statetype name="themelocation">
                        <area>0,0,30,30</area>
                        <state name="local">
                            <shape name="location">
                                <area>0,0,30,30</area>
                                <type>ellipse</type>
                                <fill color="#00FF00" />
                            </shape>
                        </state>
                        <state name="remote">
                            <shape name="location">
                                <area>0,0,30,30</area>
                                <type>ellipse</type>
                                <fill color="#FF0000" />
                            </shape>
                        </state>
                    </statetype>
-->

<!-- State to indicate whether an installed downloadable theme is up to date or not
                    <statetype name="themestatus">
                        <area>0,30,60,30</area>
                        <state name="uptodate">
                            <shape name="status">
                                <area>0,0,60,30</area>
                                <type>ellipse</type>
                                <fill color="#00FF00" />
                            </shape>
                        </state>
                        <state name="updateavailable">
                            <shape name="status">
                                <area>0,0,60,30</area>
                                <type>ellipse</type>
                                <fill color="#0000FF" />
                            </shape>
                        </state>
                    </statetype>
-->
                </state>

                <state name="selectedactive" from="active">
                    <shape name="item">
                        <fill color="#0767AB" alpha="240" />
                    </shape>
                    <textarea name="buttontext">
                        <alpha>200</alpha>
                        <font>basesmall</font>
                    </textarea>
                    <imagetype name="buttonimage">
                        <alpha>255</alpha>
                    </imagetype>
                    <imagetype name="divider">
                        <filename />
                    </imagetype>
                </state>
                <state name="selectedinactive" from="active" />
            </statetype>
            <statetype name="upscrollarrow">
                <position>325,490</position>
                <state type="off">
                </state>
                <state type="full">
                    <imagetype name="upon">
                        <filename>lb-uparrow-reg.png</filename>
                        <alpha>230</alpha>
                    </imagetype>
                </state>
            </statetype>
            <statetype name="downscrollarrow">
                <position>343,490</position>
                <state type="off">
                </state>
                <state type="full">
                    <imagetype name="dnon">
                        <filename>lb-dnarrow-reg.png</filename>
                        <alpha>230</alpha>
                    </imagetype>
                </state>
            </statetype>
        </buttonlist>

<!-- a progressbar to display the progress of the theme download
        <progressbar name="downloadprogressbar" from="baseprogressbar">
            <area>40,540,375,20</area>
        </progressbar>
-->

        <statetype name="fullpreviewstate">
            <area>0,0,800,600</area>
            <state name="fullscreen">
                <area>0,0,800,600</area>
                <imagetype name="fullscreenpreview">
                    <area>0,0,800,600</area>
                    <filename />
                </imagetype>

                <shape name="fullscreennameback" from="basebackground">
                    <area>275,10,250,66</area>
                    <fill color="#000000" alpha="220" />
                </shape>

                <textarea name="fullscreenname" from="basetextarea">
                    <area>283,18,234,50</area>
                    <multiline>no</multiline>
                    <font>basemediumgreen</font>
                    <align>center,vcenter</align>
                </textarea>
            </state>
        </statetype>

    </window>

</mythuitheme>

=== stinger151/mythtv/mythplugins/mythgame/theme/default/game-ui.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mythuitheme SYSTEM "http://www.mythtv.org/schema/mythuitheme.dtd">
<mythuitheme>

  <window name="gameui">

    <imagetype name="fanart">
        <area>0,0,800,600</area>
    </imagetype>

    <buttontree name="gametreelist">
        <area>0,10,800,310</area>
        <numlists>2</numlists>
        <spacing>10</spacing>
        <buttonlist name="listtemplate" from="basebuttonlist" />
    </buttontree>

    <textarea name="title" from="basetextarea">
        <area>38,360,500,50</area>
        <font>baseextralarge</font>
    </textarea>

    <textarea name="systemlabel" from="basetextarea">
        <area>38,430,150,35</area>
        <value>System:</value>
    </textarea>

    <textarea name="system" from="basetextarea">
        <area>178,430,500,35</area>
    </textarea>

    <textarea name="yearlabel" from="systemlabel">
        <position>38,465</position>
        <value>Year:</value>
    </textarea>

    <textarea name="year" from="system">
        <position>178,465</position>
    </textarea>

    <textarea name="genrelabel" from="systemlabel">
        <position>38,495</position>
        <value>Genre:</value>
    </textarea>

    <textarea name="genre" from="system">
        <position>178,495</position>
    </textarea>

    <textarea name="favoritelabel" from="systemlabel">
        <position>38,525</position>
        <value>Favorite:</value>
    </textarea>

    <statetype name="favorite">
        <state name="no">
            <textarea name="favorite" from="basetextarea">
                <area>178,525,500,35</area>
                <value>No</value>
            </textarea>
        </state>
        <state name="yes" from="no">
            <textarea name="favorite">
                <value>Yes</value>
            </textarea>
        </state>
    </statetype>

    <textarea name="description" from="system">
        <position>38,565</position>
    </textarea>

    <imagetype name="screenshot">
        <area>600,420,180,150</area>
    </imagetype>

    <imagetype name="coverart">
        <area>410,420,180,150</area>
        <preserveaspect>true</preserveaspect>
    </imagetype>

  </window>

  <window name="edit_metadata">

    <textarea name="title" from="basetextarea">
        <area>10,50,1260,50</area>
        <value>Edit Game Information</value>
        <align>hcenter,vcenter</align>
        <font>baselarge</font>
    </textarea>

    <!-- Labels -->

    <textarea name="gamename_label" from="basetextarea">
        <area>25,110,250,40</area>
        <value>Game Name:</value>
        <align>right,top</align>
    </textarea>

    <textarea name="genre_label" from="basetextarea">
        <area>25,155,250,40</area>
        <value>Genre:</value>
        <align>right,top</align>
    </textarea>

    <textarea name="year_label" from="basetextarea">
        <area>25,200,250,40</area>
        <value>Year:</value>
        <align>right,top</align>
    </textarea>

    <textarea name="country_label" from="basetextarea">
        <area>25,245,250,40</area>
        <value>Country:</value>
        <align>right,top</align>
    </textarea>

    <textarea name="publisher_label" from="basetextarea">
        <area>25,290,250,40</area>
        <value>Publisher:</value>
        <align>right,top</align>
    </textarea>

    <textarea name="plot_label" from="basetextarea">
        <area>25,335,250,40</area>
        <value>Plot:</value>
        <align>right,top</align>
    </textarea>

    <textarea name="favorite_label" from="basetextarea">
        <area>25,385,250,40</area>
        <value>Favorite:</value>
        <align>right,top</align>
    </textarea>

    <textarea name="screenshot_label" from="basetextarea">
        <area>25,430,250,40</area>
        <value>Screenshot:</value>
        <align>right,top</align>
    </textarea>

    <textarea name="fanart_label" from="basetextarea">
        <area>25,475,250,40</area>
        <value>Fanart:</value>
        <align>right,top</align>
    </textarea>

    <textarea name="coverart_label" from="basetextarea">
        <area>25,520,250,40</area>
        <value>Boxart:</value>
        <align>right,top</align>
    </textarea>

    <!-- Widgets -->

    <textedit name="title_edit" from="basetextedit">
        <position>285,100</position>
    </textedit>

    <textedit name="genre_edit" from="basetextedit">
        <position>285,145</position>
    </textedit>

    <textedit name="year_edit" from="basetextedit">
        <position>285,190</position>
    </textedit>

    <textedit name="country_edit" from="basetextedit">
        <position>285,235</position>
    </textedit>

    <textedit name="publisher_edit" from="basetextedit">
        <position>285,280</position>
    </textedit>

    <textedit name="description_edit" from="basetextedit">
        <position>285,325</position>
    </textedit>

    <checkbox name="favorite_check" from="basecheckbox">
        <position>285,380</position>
    </checkbox>

    <button name="screenshot_button" from="basesearchbutton">
        <position>285,420</position>
    </button>

    <textarea name="screenshot_text" from="basetextarea">
        <area>325,425,250,40</area>
        <value>/path/to/the/thing.jpg</value>
    </textarea>

    <button name="fanart_button" from="basesearchbutton">
        <position>285,465</position>
    </button>

    <textarea name="fanart_text" from="basetextarea">
        <area>325,470,250,40</area>
        <value>/path/to/the/thing.jpg</value>
    </textarea>

    <button name="coverart_button" from="basesearchbutton">
        <position>285,510</position>
    </button>

    <textarea name="coverart_text" from="basetextarea">
        <area>325,515,250,40</area>
        <value>/path/to/the/thing.jpg</value>
    </textarea>

    <button name="done_button" from="basebutton">
        <position>285,565</position>
        <value>Done</value>
    </button>

  </window>

  <window name="gamedetailspopup">

    <imagetype name="fanart">
        <area>0,0,800,600</area>
    </imagetype>

    <textarea name="gamename_lab" from="basetextarea">
        <area>40,60,140,40</area>
        <value>Game:</value>
        <align>right</align>
    </textarea>

    <textarea name="title" from="basetextarea">
        <area>190,60,570,40</area>
    </textarea>

    <textarea name="gametype_lab" from="basetextarea">
        <area>40,100,140,40</area>
        <value>Type:</value>
        <align>right</align>
    </textarea>

    <textarea name="gametype" from="basetextarea">
        <area>190,100,570,40</area>
    </textarea>

    <textarea name="romname_lab" from="basetextarea">
        <area>40,140,140,40</area>
        <value>Filename:</value>
        <align>right</align>
    </textarea>

    <textarea name="romname" from="basetextarea">
        <area>190,140,570,40</area>
    </textarea>

    <textarea name="rompath_lab" from="basetextarea">
        <area>40,180,140,40</area>
        <value>ROM path:</value>
        <align>right</align>
    </textarea>

    <textarea name="rompath" from="basetextarea">
        <area>190,180,570,40</area>
    </textarea>

    <textarea name="allsystems_lab" from="basetextarea">
        <area>40,220,140,40</area>
        <value>System(s):</value>
        <align>right</align>
    </textarea>

    <textarea name="allsystems" from="basetextarea">
        <area>190,220,570,40</area>
    </textarea>

    <textarea name="genre_lab" from="basetextarea">
        <area>40,260,140,40</area>
        <value>Genre:</value>
        <align>right</align>
    </textarea>

    <textarea name="genre" from="basetextarea">
        <area>190,260,570,40</area>
    </textarea>

    <textarea name="year_lab" from="basetextarea">
        <area>40,300,140,40</area>
        <value>Year:</value>
        <align>right</align>
    </textarea>

    <textarea name="year" from="basetextarea">
        <area>190,300,400,40</area>
    </textarea>

    <textarea name="country_lab" from="basetextarea">
        <area>40,340,140,40</area>
        <value>Country:</value>
        <align>right</align>
    </textarea>

    <textarea name="country" from="basetextarea">
        <area>190,340,400,40</area>
    </textarea>

    <textarea name="publisher_lab" from="basetextarea">
        <area>40,380,140,40</area>
        <value>Publisher:</value>
        <align>right</align>
    </textarea>

    <textarea name="publisher" from="basetextarea">
        <area>190,380,400,40</area>
    </textarea>

    <textarea name="crc_lab" from="basetextarea">
        <area>40,420,140,40</area>
        <value>CRC:</value>
        <align>right</align>
    </textarea>

    <textarea name="crc" from="basetextarea">
        <area>190,420,400,40</area>
    </textarea>

    <textarea name="description" from="basetextarea">
        <area>40,470,640,40</area>
        <value>No Plot.</value>
        <align>left</align>
    </textarea>

    <imagetype name="coverart">
        <area>600,300,180,150</area>
        <preserveaspect>true</preserveaspect>
    </imagetype>

    <button name="play_button" from="basebutton">
        <position>118,517</position>
        <value>Play</value>
    </button>

    <button name="done_button" from="basebutton">
        <position>529,517</position>
        <value>Done</value>
    </button>

  </window>

</mythuitheme>
