=== stinger151/mythtv/mythtv/themes/mythuitheme.dtd
<!-- Parameter entities to avoid repetition -->
<!ENTITY % common_attributes "name CDATA #REQUIRED
                              from CDATA #IMPLIED" >
<!ENTITY % widgets "textarea|imagetype|statetype|button|buttonlist|buttontree|
                    textedit|checkbox|spinbox|progressbar|clock|webbrowser|
                    shape|guidegrid|editbar" >
<!ENTITY % widget_common "area|position|alpha|alphapulse|helptext|focusorder|
                           minsize|loadondemand" >

<!-- MythUI Theme Root -->
<!ELEMENT mythuitheme (window|fontdef|%widgets;)*>

<!-- Font Definition -->
<!ELEMENT fontdef (pixelsize|size|color|shadowcolor|shadowoffset|shadowalpha|
                   outlinecolor|outlinesize|outlinealpha|weight|
                   letterspacing|wordspacing|decoration)*>
<!ATTLIST fontdef %common_attributes;
                  face CDATA #IMPLIED>
<!ELEMENT pixelsize  (#PCDATA)>
<!ELEMENT size  (#PCDATA)>
<!ELEMENT color  (#PCDATA)>
<!ELEMENT shadowcolor  (#PCDATA)>
<!ELEMENT shadowoffset  (#PCDATA)>
<!ELEMENT shadowalpha  (#PCDATA)>
<!ELEMENT outlinecolor  (#PCDATA)>
<!ELEMENT outlinesize  (#PCDATA)>
<!ELEMENT outlinealpha  (#PCDATA)>
<!ELEMENT weight  (#PCDATA)>
<!ELEMENT letterspacing  (#PCDATA)>
<!ELEMENT wordspacing  (#PCDATA)>
<!ELEMENT decoration  (#PCDATA)>

<!-- Window/Screen -->
<!ELEMENT window (%widget_common;|fontdef|%widgets;)*>
<!ATTLIST window %common_attributes;>

<!-- Elements common to all widgets -->
<!ELEMENT area (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT alpha (#PCDATA)>
<!ELEMENT alphapulse EMPTY>
<!ATTLIST alphapulse min CDATA "0"
                     max CDATA "255"
                     change CDATA "5">
<!ELEMENT helptext (#PCDATA)>
<!ATTLIST helptext lang CDATA #IMPLIED>
<!ELEMENT focusorder (#PCDATA)>
<!ELEMENT minsize (#PCDATA)>
<!ELEMENT loadondemand (#PCDATA)>

<!-- Textarea Widget -->
<!ENTITY % textarea_elements "(case|font|cutdown|multiline|align|colorcycle|
                               scroll|value|template)">
<!ELEMENT textarea (%widget_common;|%textarea_elements;|%widgets;)*>
<!ATTLIST textarea %common_attributes;>
<!ELEMENT case (#PCDATA)>
<!ELEMENT font (#PCDATA)>
<!ATTLIST font state CDATA #IMPLIED>
<!ELEMENT cutdown (#PCDATA)>
<!ELEMENT multiline (#PCDATA)>
<!ELEMENT align (#PCDATA)>
<!ELEMENT colorcycle (#PCDATA)>
<!ATTLIST colorcycle start CDATA #IMPLIED
                     end CDATA #IMPLIED
                     steps CDATA #IMPLIED>
<!ELEMENT scroll (#PCDATA)> <!-- Not yet working -->
<!ATTLIST scroll direction (left|right|up|down) "left">
<!ELEMENT value (#PCDATA)>
<!ATTLIST value lang CDATA #IMPLIED>
<!ELEMENT template (#PCDATA)>
<!ATTLIST template type CDATA #IMPLIED>

<!-- Imagetype Widget -->
<!ELEMENT imagetype (%widget_common;|filename|alpha|preserveaspect|crop|
                     mask|reflection|grayscale|filepattern|delay|%widgets;)*>
<!ATTLIST imagetype %common_attributes;>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT preserveaspect (#PCDATA)>
<!ELEMENT crop (#PCDATA)>
<!ELEMENT mask (#PCDATA)>
<!ELEMENT reflection EMPTY>
<!ATTLIST reflection axis CDATA "horizontal"
                     shear CDATA "0"
                     scale CDATA "100"
                     length CDATA "100"
                     spacing CDATA "0">
<!ELEMENT grayscale (#PCDATA)>
<!ELEMENT greyscale (#PCDATA)>
<!ELEMENT filepattern (#PCDATA)>
<!ATTLIST filepattern low CDATA "0"
                       high CDATA #REQUIRED
                       cycle (start|reverse) "start"> <!-- delay CDATA "500" -->
<!ELEMENT delay (#PCDATA)>  <!-- DEPRECATED in future? Should be attribute of filepattern. -->

<!-- Shape Widget -->
<!ELEMENT shape (%widget_common;|type|cornerradius|fill|line|%widgets;)*>
<!ATTLIST shape %common_attributes;>
<!ELEMENT type (#PCDATA)>
<!ELEMENT fill (gradient*)>
<!ATTLIST fill color CDATA #IMPLIED
               alpha CDATA #IMPLIED
               style (solid|gradient) "solid">
<!ELEMENT gradient (stop*)>
<!ATTLIST gradient start CDATA #IMPLIED
                   end CDATA #IMPLIED
                   alpha CDATA #IMPLIED
                   direction (vertical|horizontal|diagonal) "vertical">
<!ELEMENT stop (#PCDATA)>
<!ATTLIST stop position CDATA #REQUIRED
               color CDATA #REQUIRED
               alpha CDATA #IMPLIED>
<!ELEMENT line (#PCDATA)>
<!ATTLIST line color CDATA "#000000"
               alpha CDATA "255"
               width CDATA "1"
               style (solid) "solid">
<!ELEMENT cornerradius (#PCDATA)>

<!-- Statetype Widget -->
<!ELEMENT statetype (%widget_common;|showempty|state|%widgets;)*>
<!ATTLIST statetype %common_attributes;>
<!ELEMENT showempty (#PCDATA)>
<!ELEMENT state (%widget_common;|fontdef|%widgets;)*>
<!ATTLIST state name CDATA #IMPLIED
                type CDATA #IMPLIED
                from CDATA #IMPLIED>

<!-- Clock Widget -->
<!ELEMENT clock (%widget_common;|%textarea_elements;|
                 %widgets;)*>
<!ATTLIST clock %common_attributes;>

<!-- Button Widget -->
<!ELEMENT button (%widget_common;|value|%widgets;)*> <!-- statetype -->
<!ATTLIST button %common_attributes;>

<!-- Buttonlist Widget -->
<!ENTITY % buttonlist_elements "layout|spacing|arrange|align|scrollstyle|
                                wrapstyle|showarrow|buttonarea|drawfrombottom">
<!ELEMENT buttonlist (%widget_common;|%buttonlist_elements;|%widgets;)*> <!-- statetype -->
<!ATTLIST buttonlist %common_attributes;>
<!ELEMENT layout (#PCDATA)>
<!ELEMENT spacing (#PCDATA)>
<!ELEMENT arrange (#PCDATA)>
<!ELEMENT scrollstyle (#PCDATA)>
<!ELEMENT wrapstyle (#PCDATA)>
<!ELEMENT showarrow (#PCDATA)>
<!ELEMENT buttonarea (#PCDATA)>
<!ELEMENT drawfrombottom (#PCDATA)>

<!-- Buttontree Widget -->
<!ELEMENT buttontree (%widget_common;|numlists|spacing|%widgets;)*> <!-- buttonlist -->
<!ATTLIST buttontree %common_attributes;>
<!ELEMENT numlists  (#PCDATA)>

<!-- Textedit Widget -->
<!ELEMENT textedit (%widget_common;|%widgets;)*> <!-- textarea|statetype|imagetype -->
<!ATTLIST textedit %common_attributes;>

<!-- Checkbox Widget -->
<!ELEMENT checkbox (%widget_common;|%widgets;)*> <!-- statetype -->
<!ATTLIST checkbox %common_attributes;>

<!-- Spinbox Widget -->
<!ELEMENT spinbox (%widget_common;|%buttonlist_elements;|template|%widgets;)*> <!-- statetype -->
<!ATTLIST spinbox %common_attributes;>

<!-- Progressbar Widget -->
<!ELEMENT progressbar (%widget_common;|layout|style|%widgets;)*> <!-- imagetype -->
<!ATTLIST progressbar %common_attributes;>
<!ELEMENT style (#PCDATA)>

<!-- Guidegrid Widget -->
<!ELEMENT guidegrid (%widget_common;|layout|channels|timeslots|solidcolor|
                     selector|showcategories|categoryalpha|recordingcolor|
                     conflictingcolor|cutdown|multiline|textoffset|recordstatus|
                     arrow|font|%widgets;)*>
<!ATTLIST guidegrid %common_attributes;>
<!ELEMENT channels  (#PCDATA)>
<!ELEMENT timeslots  (#PCDATA)>
<!ELEMENT solidcolor  (#PCDATA)>
<!ELEMENT selector EMPTY>
<!ATTLIST selector type (highlight|box|roundbox) #IMPLIED
                   linecolor CDATA #IMPLIED
                   fillcolor CDATA #IMPLIED>
<!ELEMENT showcategories  (#PCDATA)>
<!ELEMENT categoryalpha  (#PCDATA)>
<!ELEMENT recordingcolor  (#PCDATA)>
<!ELEMENT conflictingcolor  (#PCDATA)>
<!ELEMENT textoffset  (#PCDATA)>
<!ELEMENT recordstatus EMPTY>
<!ATTLIST recordstatus type (SingleRecord|TimeslotRecord|ChannelRecord|
                             AllRecord|WeekslotRecord|FindOneRecord|
                             OverrideRecord) #REQUIRED
                       image CDATA #REQUIRED>
<!ELEMENT arrow EMPTY>
<!ATTLIST arrow direction (left|right) #REQUIRED
                image CDATA #REQUIRED>

<!-- Webbrowser Widget -->
<!ELEMENT webbrowser (%widget_common;|url|zoom|background|userstylesheet|
                      updateinterval|%widgets;)*>
<!ATTLIST webbrowser %common_attributes;>
<!ELEMENT url (#PCDATA)>
<!ELEMENT zoom (#PCDATA)>
<!ELEMENT background (#PCDATA)>
<!ATTLIST background color CDATA #REQUIRED
                     alpha CDATA #IMPLIED>
<!ELEMENT userstylesheet (#PCDATA)>
<!ELEMENT updateinterval (#PCDATA)>

<!-- Editbar Widget -->
<!ELEMENT editbar (%widget_common;|%widgets;)*>
<!ATTLIST editbar %common_attributes;>

=== stinger151/mythtv/mythtv/themes/Terra/netvision-ui.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mythuitheme SYSTEM "http://www.mythtv.org/schema/mythuitheme.dtd">
<mythuitheme>

    <window name="browser">

        <imagetype name="fanart" from="basebackdrop" />

        <imagetype name="topbar" from="basetopbar" />

        <textarea name="heading" from="baseheading">
            <value>Internet Video Browser</value>
        </textarea>

        <imagetype name="browserbackground">
            <position>0,345</position>
            <filename>video/browserlistbackground.png</filename>
        </imagetype>

        <buttonlist name="videos">
            <area>0,345,1280,299</area>
            <layout>horizontal</layout>
            <scrollstyle>center</scrollstyle>
            <wrapstyle>items</wrapstyle>
            <buttonarea>0,0,1282,299</buttonarea>
            <spacing>0</spacing>
            <statetype name="buttonitem">
                <state name="selectedactive">
                    <area>-13,0,209,332</area>
                    <imagetype name="buttonimage">
                        <area>1,3,209,325</area>
                        <preserveaspect>true</preserveaspect>
                        <mask>video/postermask.png</mask>
                    </imagetype>

                    <shape name="titlebackground" />
                    <textarea name="buttontext" />

                    <statetype name="nodetype">
                        <position>134,255</position>
                        <state name="subfolder">
                            <imagetype name="icon">
                                <filename>shared/directory.png</filename>
                            </imagetype>
                        </state>
                        <state name="upfolder" from="subfolder">
                            <imagetype name="arrow">
                                <position>38,33</position>
                                <filename>shared/updirectory.png</filename>
                            </imagetype>
                        </state>
                    </statetype>

                    <textarea name="childcount" from="basetextarea">
                        <area>160,290,35,20</area>
                        <font>basesmallbrown</font>
                        <align>hcenter</align>
                    </textarea>

                </state>
                <state name="active" from="selectedactive">
                    <area>0,0,183,332</area>
                    <imagetype name="buttonimage">
                        <area>0,25,183,275</area>
                        <preserveaspect>true</preserveaspect>
                    </imagetype>

                    <shape name="titlebackground">
                        <area>0,0,183,25</area>
                        <fill color="#767662" alpha="180" />
                    </shape>

                    <textarea name="buttontext" from="basetextarea">
                        <area>5,2,173,20</area>
                        <align>hcenter</align>
                    </textarea>

                    <statetype name="nodetype">
                        <position>108,230</position>
                    </statetype>

                    <textarea name="childcount">
                        <position>135,265</position>
                    </textarea>

                </state>
            </statetype>
        </buttonlist>

        <imagetype name="posterframe">
            <position>0,340</position>
            <filename>video/browserlistframe.png</filename>
        </imagetype>

        <shape name="textbackground" from="basetextbackground">
            <position>30,70</position>
        </shape>

        <textarea name="title" from="basetextarea">
            <area>48,75,590,35</area>
            <font>baselarge</font>
        </textarea>

        <textarea name="description" from="basetextarea">
            <area>48,124,1182,145</area>
            <multiline>yes</multiline>
            <align>vcenter</align>
        </textarea>

        <textarea name="nosites" from="description">
            <align>allcenter</align>
            <value>No sites configured!</value>
        </textarea>

        <textarea name="year" from="basetextarea">
            <area>48,284,290,30</area>
        </textarea>

        <textarea name="author" from="basetextarea">
            <area>430,284,800,30</area>
            <align>right</align>
        </textarea>

    </window>

    <window name="gallery">

        <imagetype name="fanart" from="basebackdrop" />

        <imagetype name="topbar" from="basetopbar" />

        <textarea name="heading" from="baseheading">
            <value>Videos - Gallery</value>
        </textarea>

        <buttonlist name="videos">
            <area>17,55,1250,520</area>
            <layout>grid</layout>
            <spacing>10</spacing>
            <buttonarea>0,0,1250,450</buttonarea>
            <statetype name="buttonitem">
                <state name="active">
                    <area>0,0,200,209</area>
                    <imagetype name="buttonbackground">
                        <filename>video/video_gallery_background.png</filename>
                    </imagetype>

                    <imagetype name="buttonimage">
                        <area>6,5,187,145</area>
                        <preserveaspect>true</preserveaspect>
                    </imagetype>

                    <statetype name="nodetype">
                        <position>118,83</position>
                        <state name="subfolder">
                            <imagetype name="icon">
                                <filename>shared/directory.png</filename>
                                <preserveaspect>yes</preserveaspect>
                            </imagetype>
                        </state>
                        <state name="upfolder" from="subfolder">
                            <imagetype name="upnode">
                                <position>37,34</position>
                                <filename>shared/updirectory.png</filename>
                            </imagetype>
                        </state>
                    </statetype>
                    <textarea name="buttontext" from="basetextarea">
                        <area>8,155,183,50</area>
                        <align>hcenter,vcenter</align>
                        <multiline>true</multiline>
                    </textarea>
                    <textarea name="childcount" from="basetextarea">
                        <area>144,118,35,20</area>
                        <font>basesmallbrown</font>
                        <align>hcenter</align>
                    </textarea>
                </state>
                <state name="selectedactive" from="active">
                    <imagetype name="buttonbackground">
                        <filename>video/video_gallery_background_selected.png</filename>
                    </imagetype>
                </state>
            </statetype>
        </buttonlist>

        <textarea name="nosites" from="basetextarea">
            <area>50,50,700,50</area>
            <multiline>yes</multiline>
            <align>hcenter,vcenter</align>
            <value>No sites configured!</value>
        </textarea>

        <shape name="textbackground" from="basetextbackground">
            <area>30,490,1222,188</area>
            <shape name="hline2" from="hline">
                <position>15,152</position>
            </shape>
        </shape>

        <textarea name="title" from="basetextarea">
            <area>48,497,590,35</area>
            <font>baselarge</font>
        </textarea>

        <textarea name="description" from="basetextarea">
            <area>48,535,1182,110</area>
            <multiline>yes</multiline>
            <align>vcenter</align>
        </textarea>

        <textarea name="year" from="basetextarea">
            <area>48,650,290,30</area>
        </textarea>

        <textarea name="author" from="basetextarea">
            <area>430,650,800,30</area>
            <align>right</align>
        </textarea>

    </window>

    <window name="tree">

        <imagetype name="topbar" from="basetopbar" />

        <textarea name="heading" from="baseheading">
            <value>Videos - Tree</value>
        </textarea>

        <textarea name="breadcrumbs" from="basetextarea">
            <area>50,20,700,40</area>
            <font>basemedium</font>
        </textarea>

        <buttontree name="videos">
            <area>40,50,720,260</area>
            <numlists>3</numlists>
            <spacing>10</spacing>
            <buttonlist name="listtemplate" from="basebuttonlist" />
        </buttontree>

        <textarea name="title" from="basetextarea">
            <area>40,330,530,40</area>
            <font>baselarge</font>
        </textarea>

        <textarea name="author" from="basetextarea">
            <area>50,367,450,30</area>
        </textarea>

        <textarea name="date" from="basetextarea">
            <area>500,367,80,30</area>
            <align>right</align>
        </textarea>

        <textarea name="description" from="basetextarea">
            <area>40,395,530,80</area>
            <align>left,top</align>
            <multiline>yes</multiline>
            <cutdown>yes</cutdown>
        </textarea>

        <textarea name="nosites" from="description">
            <align>allcenter</align>
            <value>No sites configured!</value>
        </textarea>

        <imagetype name="preview">
            <area>624,335,140,212</area>
            <preserveaspect>yes</preserveaspect>
        </imagetype>

    </window>

</mythuitheme>
<!-- vim: set expandtab ts=4 sw=4 : -->

=== stinger151/mythtv/mythtv/themes/Terra/status-ui.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mythuitheme SYSTEM "http://www.mythtv.org/schema/mythuitheme.dtd">
<mythuitheme>

    <window name="status">

        <imagetype name="backdrop" from="basebackdrop" />

        <imagetype name="topbar" from="basetopbar" />

        <textarea name="sched" from="baseheading">
            <value>System Status</value>
        </textarea>

        <buttonlist name="category">
            <area>39,97,600,588</area>
            <layout>vertical</layout>
            <spacing>0</spacing>
            <buttonarea>25,0,600,588</buttonarea>
            <statetype name="buttonitem">
                <area>0,0,595,84</area>
                <state name="active">
                    <area>0,0,595,84</area>
                    <imagetype name="statusimage">
                        <filename>shared/disabled.png</filename>
                    </imagetype>
                    <imagetype name="frame">
                        <filename>recordings/generallistbackground.png</filename>
                    </imagetype>
                    <textarea name="buttontext" from="basetextarea">
                        <area>35,10,515,42</area>
                        <font>baselarge</font>
                        <align>vcenter</align>
                    </textarea>
                </state>
                <state name="selectedactive" from="active">
                    <imagetype name="frame">
                        <position>-19,0</position>
                        <filename>recordings/generallistselectedframe.png</filename>
                    </imagetype>
                    <imagetype name="statusimage">
                        <filename>shared/selected_disabled.png</filename>
                    </imagetype>
                    <textarea name="buttontext">
                        <area>37,10,555,42</area>
                    </textarea>
                </state>
                <state name="selectedinactive" from="active">
                </state>
            </statetype>
            <statetype name="upscrollarrow">
                <position>0,5</position>
                <state type="full">
                    <imagetype name="up">
                        <filename>shared/list_up_arrow.png</filename>
                    </imagetype>
                </state>
            </statetype>
            <statetype name="downscrollarrow">
                <position>0,564</position>
                <state type="full">
                    <imagetype name="down">
                        <filename>shared/list_down_arrow.png</filename>
                    </imagetype>
                </state>
            </statetype>
        </buttonlist>

        <imagetype name="groupframe">
            <position>0,57</position>
            <filename>recordings/groupframe.png</filename>
        </imagetype>

        <buttonlist name="log" from="basebuttonlist2">
            <area>670,117,500,528</area>
            <buttonarea>0,0,500,528</buttonarea>
        </buttonlist>

        <textarea name="helptext" from="basetextarea">
            <area>40,530,0,0</area>
            <value>This screen displays the status of various system components</value>
            <multiline>yes</multiline>
        </textarea>

    </window>

</mythuitheme>
